# Builds and runs unit tests for the examples
name: Test Examples

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore NuGet Packages
        run: dotnet restore Bonsai.ML.sln

      - name: Build Solution
        run: dotnet build Bonsai.ML.sln -c Release

      - name: Run Tests
        run: dotnet test Bonsai.ML.sln
